services:
  postgres-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: veebippod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d veebippod" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    image: veebippod-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/veebippod
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:

