spring.application.name=veebippod

spring.datasource.url=jdbc:postgresql://localhost:5432/veebippod
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

## Native structured JSON logging (ECS format)
#logging.structured.format.console=ecs
#logging.structured.json.add.application=veebippod
#logging.structured.json.add.environment=development

logging.file.name=logging.log
