spring.application.name=veebippod

spring.datasource.url=jdbc:postgresql://localhost:5432/veebippod
spring.datasource.username=postgres
spring.datasource.password=fumci7-vertuj-qykwiS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true